2.2/myblog/blog/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import main_site, post_create, post_update, logout_page, sing_up_page

app_name = 'blog'

urlpatterns = [
    path('', main_site, name='main_site'),
    path('create/', post_create, name='post_create'),
    path('update/<int:pk>/', post_update, name='post_update'),
    
    path('registration/', sing_up_page, name='registration'),
    path('login/', LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', logout_page, name='logout'),
]

2.2/myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

2.2/myblog/blog/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title} - by {self.author}"
    

2.2/myblog/blog/forms.py
from django import forms

from .models import BlogPost


class BlogPostForm(forms.ModelForm):
    "form to create or edit a blog post"
    class Meta:
        model = BlogPost
        fields = ['title', 'content']

2.2/myblog/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

from .models import BlogPost
from .forms import BlogPostForm


def main_site(request):
    "Main site of project"
    posts = BlogPost.objects.all()

    context = {'posts': posts}
    return render(request, 'blog/main_site.html', context)


def sing_up_page(request):
    "registration a new user"
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('blog:main_site')
    else:
        form = UserCreationForm()
    
    context = {'form': form }

    return render(request, 'blog/register.html', context)


def logout_page(request):
    "logout a user"
    logout(request)
    return redirect('blog:main_site')
  

@login_required
def post_create(request):
    "create a new blog post"
    if request.method == 'POST':
        form = BlogPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:main_site')
    else:
        form = BlogPostForm()
    
    context = {'form': form}

    return render(request, 'blog/blog_form.html', context)


@login_required
def post_update(request, pk):
    "edit post"
    post = get_object_or_404(BlogPost, pk=pk)
    if request.user != post.author:
        return redirect('blog:main_site')
    
    if request.method == "POST":
        form = BlogPostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:main_site')
    else:
        form = BlogPostForm(instance=post)
    
    context = {'form': form}

    return render(request, 'blog/blog_form.html', context)

2.2/myblog/templates/blog/blog_form.html
{% extends 'blog/main_site.html' %}

{% block content %}

<h1>{% if form.instance.pk %} Edit {% else %} Create {% endif %} Post</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

<a href="{% url 'blog:main_site' %}">Cancel</a>

{% endblock %}

2.2/myblog/templates/blog/login.html
{% extends 'blog/main_site.html' %}

{% block content %}

<h2>Login</h2>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>

<p>Don't have an account? <a href="{% url 'blog:registration' %}">Register here</a></p>

{% endblock %}

2.2/myblog/templates/blog/main_site.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My blog </title>
</head>
<body>
    <a href="{% url 'blog:main_site' %}"><h1>Blog Posts</h1></a>

    {% block content %}
    
    <nav>
        {% if user.is_authenticated %}
            <p>Welcome {{ user.username }}</p>
            <a href="{% url 'blog:logout' %}">Logout</a>
        {% else %} 
            <a href="{% url 'blog:login' %}">Login</a>
            <a href="{% url 'blog:registration' %}">Register</a>
        {% endif %}
    </nav>

    <hr>

    <a href="{% url 'blog:post_create' %}">Create New Post</a>
    <ul>
        {% for post in posts %}
            <li>
                <h3>{{ post.title }}</h3>
                <h5>Author: {{ post.author }}</h5>
                <p>{{ post.content }}</p>
                
                {% if request.user == post.author %}
                <a href="{% url 'blog:post_update' post.pk %}">Edit</a>
                {% endif %}

            </li>
            <hr>
        {% endfor %}
    </ul>

    {% endblock %}

</body>
</html>

2.2/myblog/templates/blog/register.html
{% extends 'blog/main_site.html' %}

{% block content %}
<h2> Register </h2>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>

<p>Already have an account? <a href="{% url 'blog:login' %}">Login</a></p>

{% endblock %}